/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
/* Header for class io_github_andylx96_myapplication_NativeClass */

using namespace cv;
#ifndef _Included_io_github_andylx96_myapplication_NativeClass
#define _Included_io_github_andylx96_myapplication_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_andylx96_myapplication_NativeClass
 * Method:    faceDetection
 * Signature: (J)V
 */

void detect (Mat& frame);


JNIEXPORT void JNICALL Java_io_github_andylx96_myapplication_NativeClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
